version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
    groups:
      npm-minor-patch:
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'typescript'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
    groups:
      github-actions:
        update-types:
          - 'minor'
          - 'patch'
